import 'package:flutter_test/flutter_test.dart';
import 'package:taalebin/data/content/natal_content.dart';

/// Completeness tests for the natal interpretation bank — guards against
/// regeneration drift (the bank is generated by tool/content_natal.py).
void main() {
  const signs = [
    'aries', 'taurus', 'gemini', 'cancer', 'leo', 'virgo',
    'libra', 'scorpio', 'sagittarius', 'capricorn', 'aquarius', 'pisces',
  ];
  const planets = ['mercury', 'venus', 'mars', 'jupiter', 'saturn',
    'uranus', 'neptune'];

  test('transit content covers all nine bodies', () {
    expect(NatalContent.transitThemes.keys.toSet(), {
      'sun', 'moon', 'mercury', 'venus', 'mars', 'jupiter', 'saturn',
      'uranus', 'neptune',
    });
    for (final e in NatalContent.transitThemes.entries) {
      expect(e.value.length, greaterThan(12), reason: e.key);
    }
    expect(NatalContent.transitsIntro.length, greaterThan(60));
    expect(NatalContent.transitsMethodNote.length, greaterThan(60));
  });

  test('every planet has a text for every sign', () {
    for (final planet in planets) {
      final bank = NatalContent.planetInSign[planet];
      expect(bank, isNotNull, reason: planet);
      expect(bank!.keys.toSet(), signs.toSet(), reason: planet);
      for (final sign in signs) {
        expect(bank[sign]!.length, greaterThan(60),
            reason: '$planet in $sign');
      }
    }
  });

  test('ascendant & natal Moon texts cover all twelve signs', () {
    expect(NatalContent.ascendantInSign.keys.toSet(), signs.toSet());
    expect(NatalContent.natalMoonInSign.keys.toSet(), signs.toSet());
    for (final sign in signs) {
      expect(NatalContent.ascendantInSign[sign]!.length, greaterThan(60));
      expect(NatalContent.natalMoonInSign[sign]!.length, greaterThan(60));
    }
  });

  test('all five aspect kinds have {a}/{b} placeholder templates', () {
    expect(NatalContent.aspectTexts.keys.toSet(),
        {'conjunction', 'sextile', 'square', 'trine', 'opposition'});
    for (final entry in NatalContent.aspectTexts.entries) {
      expect(entry.value.contains('{a}'), isTrue, reason: entry.key);
      expect(entry.value.contains('{b}'), isTrue, reason: entry.key);
    }
  });

  test('dominant elements and house titles are complete', () {
    expect(NatalContent.dominantElement.keys.toSet(),
        {'fire', 'earth', 'air', 'water'});
    expect(NatalContent.houseTitles.length, 12);
    for (final title in NatalContent.houseTitles) {
      expect(title.length, greaterThan(8));
    }
  });

  test('intro/method/notes are present and substantial', () {
    for (final text in [
      NatalContent.chartIntro,
      NatalContent.methodNote,
      NatalContent.noTimeNote,
      NatalContent.cityUnknownNote,
      NatalContent.retrogradeNote,
    ]) {
      expect(text.length, greaterThan(40));
    }
  });

  test('texts stay free of placeholder braces after substitution', () {
    // Aspect templates are the only place {a}/{b} are allowed.
    for (final entry in NatalContent.aspectTexts.entries) {
      final substituted = entry.value
          .replaceAll('{a}', 'خورشید')
          .replaceAll('{b}', 'ماه');
      expect(substituted.contains('{'), isFalse);
      expect(substituted.contains('}'), isFalse);
    }
  });
}
