import 'package:shamsi_date/shamsi_date.dart';

import '../../domain/horoscope/horoscope_engine.dart';
import '../../domain/horoscope/horoscope_models.dart';
import '../../domain/zodiac/zodiac_repository.dart';
import '../database/app_database.dart';
import 'profile_repository.dart';

/// Repository abstraction for horoscopes (product spec §25):
/// LocalHoroscopeRepository today; a RemoteHoroscopeRepository can be
/// swapped in later (Local base + remote content + profile data →
/// personalized horoscope, product spec §47) without UI rewrites.
abstract class HoroscopeRepository {
  /// Cache-or-generate daily horoscope for sign+date.
  Future<DailyHoroscope> dailyFor(String zodiacId, Jalali date);

  /// The seven days of the week starting at [weekStart] (Saturday).
  Future<List<DailyHoroscope>> weekFor(String zodiacId, Jalali weekStart);

  /// Monthly horoscope (cheap to compute; not cached).
  Future<MonthlyHoroscope> monthlyFor(String zodiacId, int year, int month);

  /// Drops cached rows generated by an older engine version.
  Future<int> purgeStaleCache();

  /// Full cache wipe (data reset).
  Future<void> clearCache();
}

class LocalHoroscopeRepository implements HoroscopeRepository {
  LocalHoroscopeRepository(this._db, this._engine, this._zodiacRepository);

  final AppDatabase _db;
  final HoroscopeEngine _engine;
  final ZodiacRepository _zodiacRepository;

  @override
  Future<DailyHoroscope> dailyFor(String zodiacId, Jalali date) async {
    final dayKey =
        '${date.year}-${_two(date.month)}-${_two(date.day)}';
    final cached = _db.dailyHoroscope(zodiacId, dayKey);
    if (cached != null) {
      final row = _fromRow(cached);
      if (row.generatedVersion == kHoroscopeGeneratedVersion) return row;
    }
    final sign = _zodiacRepository.byIdOrFail(zodiacId);
    final generated = _engine.generateDaily(sign, date);
    _db.cacheDailyHoroscope(_toRow(generated));
    return generated;
  }

  @override
  Future<List<DailyHoroscope>> weekFor(
      String zodiacId, Jalali weekStart) async {
    final result = <DailyHoroscope>[];
    for (var i = 0; i < 7; i++) {
      final date = Jalali.fromDateTime(
        weekStart.toDateTime().add(Duration(days: i)),
      );
      result.add(await dailyFor(zodiacId, date));
    }
    return result;
  }

  @override
  Future<MonthlyHoroscope> monthlyFor(
      String zodiacId, int year, int month) async {
    final sign = _zodiacRepository.byIdOrFail(zodiacId);
    return _engine.generateMonthly(sign, year, month);
  }

  @override
  Future<int> purgeStaleCache() async =>
      _db.purgeStaleHoroscopes(kHoroscopeGeneratedVersion);

  @override
  Future<void> clearCache() async {
    _db.clearHoroscopeCache();
  }

  static Map<String, Object?> _toRow(DailyHoroscope h) => {
        'id': generateId(),
        'zodiac_id': h.zodiacId,
        'date': h.date,
        'love_score': h.scores.love,
        'career_score': h.scores.career,
        'finance_score': h.scores.finance,
        'mood_score': h.scores.mood,
        'energy_score': h.scores.energy,
        'general_text': h.generalText,
        'love_text': h.loveText,
        'career_text': h.careerText,
        'finance_text': h.financeText,
        'mood_text': h.moodText,
        'warning_text': h.warningText,
        'opportunity_text': h.opportunityText,
        'lucky_color': h.lucky.color,
        'lucky_number': h.lucky.number,
        'lucky_time': h.lucky.time,
        'generated_version': h.generatedVersion,
        'created_at': DateTime.now().toUtc().toIso8601String(),
      };

  static DailyHoroscope _fromRow(Map<String, Object?> row) => DailyHoroscope(
        zodiacId: row['zodiac_id']! as String,
        date: row['date']! as String,
        scores: DailyScores(
          love: row['love_score']! as int,
          career: row['career_score']! as int,
          finance: row['finance_score']! as int,
          mood: row['mood_score']! as int,
          energy: row['energy_score']! as int,
        ),
        lucky: LuckyInfo(
          color: row['lucky_color']! as String,
          number: row['lucky_number']! as int,
          time: row['lucky_time']! as String,
        ),
        generalText: row['general_text']! as String,
        loveText: row['love_text']! as String,
        careerText: row['career_text']! as String,
        financeText: row['finance_text']! as String,
        moodText: row['mood_text']! as String,
        warningText: row['warning_text']! as String,
        opportunityText: row['opportunity_text']! as String,
        generatedVersion: row['generated_version']! as int,
      );

  static String _two(int v) => v.toString().padLeft(2, '0');
}
