# تنظیمات Gradle
# مقدار حافظه ماشین مجازی Gradle را بر اساس RAM سیستم خود تنظیم کنید.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# استفاده از AndroidX
android.useAndroidX=true

# کلاس‌های R غیرهم‌نام (non-transitive)
android.nonTransitiveRClass=true

# سبک کد Kotlin
kotlin.code.style=official

# کش بیلد
org.gradle.caching=true
