name: nameology_app
description: "علم اسامی؛ دانشنامه آفلاین نام‌ها، ریشه‌شناسی و تحلیل‌های سنتی"
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  path: ^1.9.0
  path_provider: ^2.1.2
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/nameology_logo.png
    - assets/images/home_hero.png
    - assets/images/archive_illustration.png
