-- ═══════════════════════════════════════════════════════════════════════════
-- open-autoDM - App settings (single-row table)
--
-- Holds the self-hoster's Meta app credentials, entered through the in-app
-- Setup Wizard. The App Secret is AES-256-GCM encrypted with the deployment's
-- TOKEN_ENCRYPTION_KEY before it is stored - never plaintext in the DB.
--
-- No RLS user policies: this table is service-role only. All reads/writes go
-- through authenticated API routes which mask/decrypt as appropriate.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE public.app_settings (
  -- Single-row table: id is always 1
  id                          INTEGER     PRIMARY KEY CHECK (id = 1),

  meta_app_id                 TEXT,
  meta_app_secret_encrypted   TEXT,       -- AES-256-GCM: iv:ciphertext:authtag
  -- Optional. Meta signs webhooks with the Instagram app secret for
  -- Instagram-Login apps but the Facebook app secret for Facebook-Login apps.
  -- Storing both lets signature verification accept either - kills a whole
  -- class of "webhook silently rejected" setup failures.
  meta_fb_app_secret_encrypted TEXT,      -- AES-256-GCM: iv:ciphertext:authtag
  webhook_verify_token        TEXT,       -- generated by the setup wizard

  setup_completed             BOOLEAN     NOT NULL DEFAULT false,

  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER app_settings_updated_at
  BEFORE UPDATE ON public.app_settings
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- Seed the singleton row so the app can always UPDATE id=1
INSERT INTO public.app_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
