/// Static list of major Iranian cities for the optional birth-city picker.
/// v1 requires no location permission — the user picks manually.
const List<String> kIranCities = [
  'تهران',
  'مشهد',
  'اصفهان',
  'شیراز',
  'تبریز',
  'کرج',
  'اهواز',
  'قم',
  'رشت',
  'کرمانشاه',
  'ارومیه',
  'زاهدان',
  'کرمان',
  'یزد',
  'بندرعباس',
  'همدان',
  'بوشهر',
  'زنجان',
  'سنندج',
  'قزوین',
  'خرم‌آباد',
  'اراک',
  'ساری',
  'بیرجند',
  'ایلام',
  'یاسوج',
  'سمنان',
  'شهرکرد',
  'بجنورد',
  'گرگان',
  'أستارا',
  'خارج از ایران',
];
